### ISSUE TITLE
Would be be better to use brackets [minor] instead of <-minor->

### ISSUE THREAD

**Issue by vbilici** [brcnblc/ci-auto-version#1]
It is more convenient to pass arguments via brackets like [skip ci] in gitlab
also, it is easier to write

**Comment by brcnblc** [comment]
I'm gonna make it parametric, so that user may specify pattern according to his/her needs. But for default I'll change it to bracket style. Wait for the next release...

**Comment by brcnblc** [comment]
**In Version 0.3.0**

- [major] ,  [minor] , [patch],  [ignore] commands are used in merge commit message.
- There is no need to use [patch] command since it is the default behavior.
- If [ignore] is provided in commit message, versioning is by-passed. (Nothing is done).

**Command line arguments, used to customize command pattern.**

```
--major-pattern, -mj <PatternString> 
  Definition : Defines commit message pattern for major version upgrade.
  Default Value : [major]

--minor-pattern, -mp <PatternString> 
  Definition : Defines commit message pattern for minor version upgrade.
  Default Value : [minor]

--patch-pattern, -pp <PatternString> 
  Definition : Defines commit message pattern for minor version upgrade.
  Default Value : [patch]

--ignore-pattern, -gp <PatternString> 
  Definition : Defines commit message pattern to bypass version upgrade.
  Default Value : [ignore]

--default-action, -df [ patch | minor | major | ignore ] 
  Definition : Defines default action when no pattern matched in commit message.
  Default Value : patch
```
